export enum WizformElementType {
    NONE = 'NONE',
    NEUTRAL_ONE = 'NEUTRAL_ONE',
    NATURE = 'NATURE',
    AIR = 'AIR',
    WATER = 'WATER',
    LIGHT = 'LIGHT',
    ENERGY = 'ENERGY',
    PSI = 'PSI',
    STONE = 'STONE',
    ICE = 'ICE',
    FIRE = 'FIRE',
    DARK = 'DARK',
    CHAOS = 'CHAOS',
    METALL = 'METALL',
    NEUTRAL_TWO = 'NEUTRAL_TWO',
    CUSTOM_1 = 'CUSTOM_1',
    CUSTOM_2 = 'CUSTOM_2',
    CUSTOM_3 = 'CUSTOM_3',
    CUSTOM_4 = 'CUSTOM_4',
    CUSTOM_5 = 'CUSTOM_5'
}